/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ag_api_math_IAgMathApi */

#ifndef _Included_com_ag_api_math_IAgMathApi
#define _Included_com_ag_api_math_IAgMathApi
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ag_api_math_IAgMathApi
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_ag_api_math_IAgMathApi_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
